spring.application.name=retail-manager

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

whatsapp.api.url=https://graph.facebook.com/v17.0/
whatsapp.token=${WHATSAPP_TOKEN:}
whatsapp.phoneNumberId=${WHATSAPP_PHONE_NUMBER_ID:}

mercadopago.access-token=${MERCADOPAGO_ACCESS_TOKEN:}
mercadopago.webhook-url=${MERCADOPAGO_WEBHOOK_URL:https://sua-url-producao.com/api/webhook/notificacao}

jwt.secret-key=${JWT_SECRET_KEY}




